#+AUTHOR: Bruno Cardoso <cardoso.bc@gmail.com>
#+DATE: 2022-02-01
#+STARTUP: indent content

* Yet Another Word Counter

A simple word counter minor-mode for achieving writing goals in Emacs.

** Installation

Clone this repo and add the =yawc= directory to your =load-path=:

#+begin_src emacs-lisp
(add-to-list 'load-path "/path/to/yawc")
(require 'yawc)
#+end_src

Or, with use-package + straight.el:

#+begin_src emacs-lisp
(use-package yawc
  :straight (yawc :host github :repo "bcardoso/yawc"))
#+end_src


** Usage

Run =M-x yawc-mode=. It will prompt the user for a writing goal for the current buffer.

When idle, =yawc= will show the current word count status in the minibuffer.

When you're done, run =M-x yawc-mode= again to disabled it.


** Customization

These custom variables should be set before enabling =yawc-mode= in the current buffer.

Run =M-x customize-group RET yawc= or edit the following variables to your liking:

- =yawc-writing-goal-default=: The default writing goal, set to 500 words.

- =yawc-lighter=: The lighter to be displayed in the mode line when the mode is enabled. Default is "YAWC".

- =yawc-show-status-when-idle=: Whether to show the current status in echo area when idle.

- =yawc-status-idle-interval=: The idle interval, in seconds, to show the current status in the echo area. Default is 5 seconds.

- =yawc-show-mode-line-indicator=: When non-nil, show a word counter indicator in the mode line.
